global:
  scrape_interval: "15s"
  scrape_timeout: "10s"

scrape_configs:
  - job_name: image_downloader_server
    scrape_interval: "5s"
    scrape_timeout: "5s"
    static_configs:
      - targets:
          - backend:3001

  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090

  - job_name: docker
    static_configs:
      - targets:
          - host.docker.internal:9323

  - job_name: postgres-exporter
    static_configs:
      - targets: ["host.docker.internal:9187"]
